### ISSUE TITLE
unable to resize

### ISSUE THREAD

**Issue by no-stack-dub-sack** [nathancahill/Split.js#106]
Hi, for some reason - I've been struggling with this. I thought it was possibly my build set up, so I created a new very small project to test this out, and I still cant get resizing to happen. The gutter shows up, but nothing happens when I click to drag. Am I missing something?

Here's my initialization: 
```js
Split(['#one', '#two'], {
    sizes: [70, 30],
    minSize: 200
});
```
here's my css:
```css
#one {
  height: 100vh;
  float: left;
  background: green;
}

#two {
  height: 100vh;
  float: right;
  background: blue;
}
```
And here's what I see:
![image](https://user-images.githubusercontent.com/18563015/31800529-7b0837ec-b50f-11e7-9657-1e594552f88b.png)

As you can see, there's just a plain white gutter with no way to grab it to resize. I've looked at the examples in the docs, and this seems pretty straightforward, so not sure what I'm missing. 

Mac OSX 10.12.6, Chrome - latest. Nothing out of the ordinary here. Any help would be appreciated! This looks like a great little package, I just can't get it to work 🙁
